---
job: generate # tells the runner what to do
config:
  name: "generate" # this is not really used anywhere currently but required by runner
process:
  # process 1
  - type: to_folder # process images to a folder
    output_folder: "output/gen"
device: cuda:0 # cpu, cuda:0, etc
generate:
  # these are your defaults you can override most of them with flags
  sampler: "flowmatch" # ignored for now, flow match will be used by default
  width: 1024
  height: 1024
  neg: "cartoon, fake, drawing, illustration, cgi, animated, anime"
  seed: 42
  guidance_scale: 8
  sample_steps: 32
  ext: ".png" # .png, .jpg, .jpeg, .webp
  prompt_file: true # if true a txt file will be created next to images with prompt strings used
  
  # Face inpainting configuration
  upper_body_inpainting: false
  face_inpainting: true
  face_prompt: "slaymnsha bslaymnsha a woman, smooth skin, make-up, model, fashion"

  prompts:
    - "slaymnsha bslaymnsha A woman, High fashion editorial. She is wearing a red party dress. front pose. Body facing the viewer. The background is a plain, light off-white color, creating a simple, clean studio setting. The lighting is soft, natural-looking, and diffused, full body"
    - "slaymnsha bslaymnsha A woman, High fashion editorial. She is wearing a blue shirt and party jeans and red sneakers. front pose. Body facing the viewer. The background is a plain, light off-white color, creating a simple, clean studio setting. The lighting is soft, natural-looking, and diffused, full body"
    - "slaymnsha bslaymnsha A woman, High fashion editorial. She is wearing a green loose zara pullover and a short skirt and green long strip heel sandal. front pose. Body facing the viewer. The background is a plain, light off-white color, creating a simple, clean studio setting. The lighting is soft, natural-looking, and diffused, full body"
    
model:
  name_or_path: "black-forest-labs/FLUX.1-dev"
  quantize: false # Whether to quantize the model weights
  quantize_te: false # Whether to quantize the text encoder
  arch: "flux"
  is_flux: true
  low_vram: false
  inference_lora_paths:
    - "output/bslaymnsha_v1/bslaymnsha_v1.safetensors"
    - "/workspace/loras/my_first_lora_v1_000001000.safetensors"
    - "/workspace/loras/mjV6.safetensors"
  inference_lora_strengths: [ 1.0, 1.0, 0.1 ] # Corresponding strengths for each LoRA